config/routes.rb
Rails.application.routes.draw do
  resources :churritos
  #get 'about' => 'pages#about', as: :about
  #get 'contact' => 'pages#contact', as: :contact
  #get 'contact' => 'pages#contact', as: :contact

  root to: 'exams#index'
  devise_for :users
  resources :exams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/churrito.rb
class Churrito < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/churritos_controller.rb
class ChurritosController < ApplicationController
  before_action :set_churrito, only: [:show, :edit, :update, :destroy]

  # GET /churritos
  # GET /churritos.json
  def index
    @churritos = Churrito.all
  end

  # GET /churritos/1
  # GET /churritos/1.json
  def show
  end

  # GET /churritos/new
  def new
    @churrito = Churrito.new
  end

  # GET /churritos/1/edit
  def edit
  end

  # POST /churritos
  # POST /churritos.json
  def create
    @churrito = Churrito.new(churrito_params)

    respond_to do |format|
      if @churrito.save
        format.html { redirect_to @churrito, notice: 'Churrito was successfully created.' }
        format.json { render :show, status: :created, location: @churrito }
      else
        format.html { render :new }
        format.json { render json: @churrito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /churritos/1
  # PATCH/PUT /churritos/1.json
  def update
    respond_to do |format|
      if @churrito.update(churrito_params)
        format.html { redirect_to @churrito, notice: 'Churrito was successfully updated.' }
        format.json { render :show, status: :ok, location: @churrito }
      else
        format.html { render :edit }
        format.json { render json: @churrito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /churritos/1
  # DELETE /churritos/1.json
  def destroy
    @churrito.destroy
    respond_to do |format|
      format.html { redirect_to churritos_url, notice: 'Churrito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_churrito
      @churrito = Churrito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def churrito_params
      params.require(:churrito).permit(:nombre, :sabor, :precio)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Creaste un Articulo.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Actualizaste un Articulo.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Un articulo se elimino.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title, :body, :desciption, :banner_image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < AplicationController
	
	def about
	end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/churritos_helper.rb
module ChurritosHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/churritos/_form.html.erb
<%= form_with(model: churrito, local: true) do |form| %>
  <% if churrito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(churrito.errors.count, "error") %> prohibited this churrito from being saved:</h2>

      <ul>
      <% churrito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :churrito_nombre %>
  </div>

  <div class="field">
    <%= form.label :sabor %>
    <%= form.text_area :sabor, id: :churrito_sabor %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :churrito_precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/churritos/edit.html.erb
<h1>Editing Churrito</h1>

<%= render 'form', churrito: @churrito %>

<%= link_to 'Show', @churrito %> |
<%= link_to 'Back', churritos_path %>

app/views/churritos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Churritos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sabor</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @churritos.each do |churrito| %>
      <tr>
        <td><%= churrito.nombre %></td>
        <td><%= churrito.sabor %></td>
        <td><%= churrito.precio %></td>
        <td><%= link_to 'Show', churrito %></td>
        <td><%= link_to 'Edit', edit_churrito_path(churrito) %></td>
        <td><%= link_to 'Destroy', churrito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Churrito', new_churrito_path %>

app/views/churritos/new.html.erb
<h1>New Churrito</h1>

<%= render 'form', churrito: @churrito %>

<%= link_to 'Back', churritos_path %>

app/views/churritos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @churrito.nombre %>
</p>

<p>
  <strong>Sabor:</strong>
  <%= @churrito.sabor %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @churrito.precio %>
</p>

<%= link_to 'Edit', edit_churrito_path(@churrito) %> |
<%= link_to 'Back', churritos_path %>

app/views/exams/_exam.html.erb
<div class='col-sm-6 col-lg-4'>
<h1></h1>
<h1></h1>
<h1></h1>
<h1></h1>
  <div class="card">
    <div class="card-block">
      <h4 class="card-title"><%= link_to exam.title, exam %></h4>  
      <p class="card-text"><%= truncate(exam.desciption, length: 130) %></p>
    </div>   
  </div>
</div>

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :exam_title %>
  </div>
  <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.url_field :banner_image_url %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :exam_body %>
  </div>

  <div class="field">
    <%= form.label :desciption %>
    <%= form.text_area :desciption, id: :exam_desciption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Actualizando Articulo</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Ver', @exam %> |
<%= link_to 'Atras', exams_path %>

app/views/exams/index.html.erb
<%= link_to 'Nuevo Articulo', new_exam_path %>
<h1></h1>
<h1></h1>
<h1></h1>
<h1></h1>
<div class="row">
  <%= render @exams %>
</div>

app/views/exams/new.html.erb
<h1>Nuevo Articulo</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Cancelar', exams_path %>

app/views/exams/show.html.erb
<div class="row">
<div class='col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center'>
  <div class="card">
  <img class="card-img-top" src ='<%= image_url @exam.banner_image_url %>'>
    <div class="card-block">
      <h1><%= @exam.title %></h1>
      <h1></h1>  
      <h1></h1>
      <h4><%= @exam.body %></h4>
      <h1></h1>
      <h1></h1>
      <p><%= @exam.desciption %></p>      
    </div>    
  </div>
</div>
</div>



<%= link_to 'Editar', edit_exam_path(@exam) %> | 
<%= link_to 'Volver', exams_path %>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
      <% if user_signed_in? %>        
        <li class="list-group-item">
          <%= link_to 'Inicio', exams_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Editar Perfil', edit_user_registration_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: "nav-link #{yield(:contact_active)}" %>
        </li>
      <% else %>
        <li class="list-group-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{yield(:blog_active)}"  %> 
        </li>
        <li class="list-group-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link #{yield(:blog_active)}"  %> 
        </li>        
      <% end %>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>    
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <% if user_signed_in? %>
      <strong><%= current_user.email %></strong>.
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Universo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name%><%= action_name%>">  
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>  	  


      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pages/about.html.erb
<h1>ABOUT PAGE</h1>